name: API Tests Automation

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🚀 Ejecutar pruebas en paralelo
        run: |
          npx newman run tests/api-tests.json --iteration-data data.json --reporters cli,junit --reporter-junit-export=newman/report1.xml &
          npx newman run tests/api-tests.json --iteration-data invalid_data.json --reporters cli,junit --reporter-junit-export=newman/report2.xml &
          npx newman run tests/api-tests.json --global-var "BASE_URL=https://fakestoreapi.com" --reporters cli,junit --reporter-junit-export=newman/report3.xml &
          wait

      - name: 📊 Publicar resultados
        uses: actions/upload-artifact@v2
        with:
          name: newman-reports
          path: newman/
